### ISSUE TITLE
ASTNode time to mathml yielding logic error

### ISSUE THREAD

**Issue by Karrenbelt** [sbmlteam/python-libsbml#20]
Input:
```
import platform
import libsbml

print('platform:', platform.platform())
print('python:', platform.python_version())
print('libsbml:', libsbml.__version__)

node = libsbml.ASTNode()
node.setType(libsbml.AST_NAME_TIME)
libsbml.writeMathMLToString(node)
```

Output:
```
platform: Linux-5.3.0-62-generic-x86_64-with-Ubuntu-19.10-eoan
python: 3.7.5
libsbml: 5.18.1
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by fbergmann** [comment]
thanks for letting us know i've confirmed this issue on other platforms as well. 

The issue comes up due to the underlying assumption. That there would always be a name associated with the elements of type AST_NAME / AST_NAME_TIME. In your example that is not the case. The workaround is to use something like: 


    import libsbml
    node = libsbml.ASTNode()
    node.setType(libsbml.AST_NAME_TIME)
    node.setName('t')
    libsbml.writeMathMLToString(node)

which would get you past this issue until there is a fix.
