### ISSUE TITLE
Inconsistent translation between `ln`, `log` and `log10` 

### ISSUE THREAD

**Issue by jmrohwer** [sbmlteam/python-libsbml#25]
When reading and SBML document, there is an inconsistency in the way the internal MathML is translated by `libsbml`. Take the following BioModel as an example:

``` python
>>> import libsbml as SBML
>>> r = SBML.SBMLReader()
>>> d = r.readSBMLFromFile('BIOMD0000000012_url.xml')
>>> m = d.getModel()
>>> a = m.getListOfRules()[0]
>>> a.getFormula()
    'tau_mRNA / log(2)'
```
Upon reading the document, MathML the `<ln/>` tag is translated to `log` in the formula (see above).

Upon writing the document with `d.toSBML()`, any `log` in the formula is back-translated to `<ln/>` in the MathML, and any `ln` in the formula is also back-translated to `<ln/>`. So both `log` and `ln` in the formula are translated to `<ln/>`.
If the formula contains `log10`, this is translated to
``` xml
<log/>
              <logbase>
                <cn type="integer"> 10 </cn>
              </logbase>
```

This creates a problem when interfacing to Python-based modelling tools such as PySCeS. In Python, `math.log` is natural logarithm while `math.log10` is base 10. `math.ln` does not exist in Python.

The inconsistencies in libsbml means that we cannot use symmetrical translation tables in PySCeS when going from MathML to numpy and numpy to MathML.

See also https://github.com/PySCeS/pysces/issues/44 and https://github.com/PySCeS/pysces/pull/45 for further discussion.

**Comment by fbergmann** [comment]
Hello Johann, 

i could go into a long explanation, why this behaves as it does (the short of it is, the expressions returned by `getFormula` have to be compatible with SBML L1) but I have a simple workaround for you that will help you. Rather than using the `getFormula` function, you could get the AST node directly, and have it be written using the `formulaToL3String`: 


    In [8]: libsbml.formulaToL3String(a.getMath())
    Out[8]: 'tau_mRNA / ln(2)'

and that way you should be able to roundtrip your expressions: 

    In [9]: libsbml.formulaToL3String(libsbml.parseL3Formula('tau / log10(2)'))
    Out[9]: 'tau / log10(2)'

    In [11]: libsbml.formulaToL3String(libsbml.parseL3Formula('tau / ln(2)'))
    Out[11]: 'tau / ln(2)'

that should be all you need, right? For the L3Parser, there is parser settings with which you can influence how elements are parsed by it.

**Comment by jmrohwer** [comment]
Thanks Frank, we were able to solve the problem with the workaround you suggested.
